# Generated by Django 4.2.1 on 2023-06-04 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_cliente_detallepedido_pedido_producto_delete_ejemplo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('currentAddress', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('municipality_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.department')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ordenDate', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('productCategory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parentCategory_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('salesCheckDetail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('unitValue', models.IntegerField()),
                ('soldUnits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('productInventory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesCheck',
            fields=[
                ('salesCheck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dateBill', models.DateField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.address')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='productInventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.productinventory'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='salesCheck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.salescheck'),
        ),
        migrations.AddField(
            model_name='product',
            name='productCategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.productcategory'),
        ),
        migrations.AddField(
            model_name='address',
            name='municipality_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.municipality'),
        ),
        migrations.AddField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
