# Generated by Django 4.2.1 on 2023-06-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_address_department_municipality_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='categoryImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
