# Generated by Django 4.2.1 on 2023-06-04 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(default='Fatima', max_length=50),
        ),
    ]
