# Generated by Django 4.2.1 on 2023-06-04 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_address_datecreated_address_neighborhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='productCategory_id',
            new_name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ordenDate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parentCategory_id',
        ),
        migrations.AddField(
            model_name='product',
            name='buyPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sellPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productCategory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.productcategory'),
        ),
    ]
