# Generated by Django 4.2.1 on 2023-06-04 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_productcategory_id_productcategory_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescheck',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salescheck',
            name='fullValue',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salescheck',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.product'),
        ),
    ]
