# Generated by Django 4.2.1 on 2023-06-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_department_indicative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='indicative',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='status_id',
        ),
    ]
