# Generated by Django 4.2.1 on 2023-06-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salescheck',
            name='address_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Escriba su direccion', max_length=50),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
