# Generated by Django 4.2.1 on 2023-06-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_salescheck_address_id_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
    ]
