# Generated by Django 4.2.1 on 2023-06-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_car_caritem_car_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesCheck',
        ),
    ]
