# Generated by Django 4.2.1 on 2023-06-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_product_buyprice_remove_product_sellprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellPrice',
            field=models.FloatField(null=True),
        ),
    ]
